-- Migration: Add Daily Reports System
-- This creates the daily_reports table for storing daily clinical synthesis reports

-- Create daily_reports table
CREATE TABLE IF NOT EXISTS daily_reports (
    id SERIAL PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    report_date DATE NOT NULL,
    summary_text JSONB NOT NULL,
    raw_data JSONB,
    report_type VARCHAR(50) DEFAULT 'daily_clinical_synthesis',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Ensure one report per user per day
    UNIQUE(user_id, report_date)
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_daily_reports_user_date ON daily_reports(user_id, report_date DESC);
CREATE INDEX IF NOT EXISTS idx_daily_reports_created_at ON daily_reports(created_at DESC);

-- Add RLS (Row Level Security) policies
ALTER TABLE daily_reports ENABLE ROW LEVEL SECURITY;

-- Policy: Users can only see their own daily reports
CREATE POLICY "Users can view own daily reports" ON daily_reports
    FOR SELECT USING (auth.uid() = user_id);

-- Policy: Users can insert their own daily reports
CREATE POLICY "Users can insert own daily reports" ON daily_reports
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Policy: Users can update their own daily reports
CREATE POLICY "Users can update own daily reports" ON daily_reports
    FOR UPDATE USING (auth.uid() = user_id);

-- Policy: Users can delete their own daily reports
CREATE POLICY "Users can delete own daily reports" ON daily_reports
    FOR DELETE USING (auth.uid() = user_id);

-- Add trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_daily_reports_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_daily_reports_updated_at
    BEFORE UPDATE ON daily_reports
    FOR EACH ROW
    EXECUTE FUNCTION update_daily_reports_updated_at();

-- Add comment for documentation
COMMENT ON TABLE daily_reports IS 'Stores daily clinical synthesis reports generated by Dr. Nexus AI';
COMMENT ON COLUMN daily_reports.summary_text IS 'JSON containing daily_observation, key_moment, and focus_area';
COMMENT ON COLUMN daily_reports.raw_data IS 'JSON containing all source data used to generate the report';
COMMENT ON COLUMN daily_reports.report_type IS 'Type of daily report (daily_clinical_synthesis)';